name: wireframe_theme_flutter
description: FLUX_WIREFRAME â€“ Flutter Wireframe Starter Tool
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  remixicon: ^1.0.0

  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1

  wireframe_theme_flutter:
    git:
      url: https://github.com/GLLB-Apps/wireframe_theme_flutter.git
      ref: v1.0.2

  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
