name: flux_wireframe_theme_cli
description: A CLI tool for scaffolding Flutter apps with wireframe theme and interactive project tour.
version: 0.1.0
homepage: https://github.com/GLLB-Apps/flux_wireframe-tool-CLI
repository: https://github.com/GLLB-Apps/flux_wireframe-tool-CLI

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  io: ^1.0.4

dev_dependencies:
  lints: ^4.0.0

executables:
  flux_wireframe: run
  flux_wireframe_tour: tour
  flux_wireframe_status: status
  flux_wireframe_doctor: doctor
  flux_wireframe_clear: clear